#!/bin/bash
# settings.json is the SSOT for what runs. Assert it and .claude/hooks/ agree,
# in BOTH directions.
#
# Why both. On 2026-09-20 this repo was wrong in each direction at once:
#
#   * `session-start.sh` was registered and running on the box -- it prints the
#     "AGENTS RUNNING" banner every session -- but was never committed. It
#     existed on one disk. A new machine, or that disk dying, loses it silently,
#     and nothing in CI noticed for ten days.
#
#   * `fleetcrown-capture.sh` / `fleetcrown-session-end.sh` were still
#     registered after the FleetCrown -> Loki rename, alongside their loki-*
#     successors. Both tokens and both hosts were still live, so every prompt
#     typed was posted TWICE, to two different products.
#
# A registration with no file and a file nobody runs are the same bug seen from
# opposite ends, so this checks both ends.

set -uo pipefail

ROOT="${1:-$(cd "$(dirname "$0")/../../.." && pwd)}"
SETTINGS="$ROOT/.claude/settings.json"
HOOKDIR="$ROOT/.claude/hooks"

[ -f "$SETTINGS" ] || { echo "no settings.json at $SETTINGS" >&2; exit 1; }

fail=0

# Loki's Fleet Runner generates these on startup and .gitignore excludes them
# deliberately (they are its output, not this repo's source). They are expected
# to be registered and absent from a fresh checkout.
generated() { case "$1" in loki-*.sh) return 0 ;; *) return 1 ;; esac; }

# --- direction 1: every registered command must exist in the repo ------------
echo "every registered hook exists:"
while IFS= read -r cmd; do
  [ -n "$cmd" ] || continue
  # Both spellings point at this repo: ~/.claude/hooks is a symlink to
  # .claude/hooks here, and install.sh is what creates it.
  rel="${cmd#\$HOME/dev/dotfiles/}"
  rel="${rel#/home/g/dev/dotfiles/}"
  rel="${rel/#\$HOME\/.claude\//.claude/}"
  rel="${rel/#\/home\/g\/.claude\//.claude/}"
  base="$(basename "$rel")"

  if generated "$base"; then
    echo "  skip $base (generated by Loki, gitignored by design)"
    continue
  fi
  if [ -f "$ROOT/$rel" ]; then
    echo "  ok   $rel"
  else
    echo "  FAIL settings.json registers '$cmd' but $rel is not in this repo." >&2
    echo "       A hook that lives on one disk is one disk failure from gone." >&2
    fail=1
  fi
done < <(jq -r '.hooks | to_entries[] | .value[]? | .hooks[]? | .command // empty' "$SETTINGS")

# --- direction 2: every hook script in the repo must be registered -----------
echo "every hook script is registered:"
registered="$(jq -r '.hooks | to_entries[] | .value[]? | .hooks[]? | .command // empty' "$SETTINGS")"
for f in "$HOOKDIR"/*.sh; do
  [ -e "$f" ] || continue
  base="$(basename "$f")"
  if printf '%s\n' "$registered" | grep -qF "/$base"; then
    echo "  ok   $base"
  else
    echo "  FAIL $base is in this repo but no settings.json event runs it." >&2
    echo "       Either register it, or delete it -- a hook nobody runs is a lie" >&2
    echo "       about what this machine does." >&2
    fail=1
  fi
done

if [ "$fail" -eq 0 ]; then
  echo "settings.json <-> hooks: ok"
else
  echo "settings.json <-> hooks: FAILED" >&2
fi
exit "$fail"
